# Generated by Django 4.2.3 on 2024-12-05 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TASK', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
