# Generated by Django 4.2.3 on 2024-12-05 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TASK', '0002_alter_tasks_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='status',
            new_name='completed',
        ),
    ]
